name: spaceblast
publish_to: 'none'
description: A SpriteWidget demo.
version: 0.9.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  spritewidget:
    path: ../spritewidget
#  path_provider: ^2.0.9
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/nebula.png
    - assets/sprites.json
    - assets/sprites.png
    - assets/starfield.png
    - assets/game_ui.png
    - assets/game_ui.json
    - assets/ui_bg_top.png
    - assets/ui_bg_bottom.png
    - assets/ui_popup.png
    - assets/music_game.mp3
    - assets/music_boss.mp3
    - assets/music_intro.mp3
    - assets/explosion_0.wav
    - assets/explosion_1.wav
    - assets/explosion_2.wav
    - assets/explosion_boss.wav
    - assets/explosion_player.wav
    - assets/laser.wav
    - assets/hit.wav
    - assets/levelup.wav
    - assets/pickup_0.wav
    - assets/pickup_1.wav
    - assets/pickup_2.wav
    - assets/pickup_powerup.wav
    - assets/click.wav
    - assets/buy_upgrade.wav
    - fonts/Orbitron-Medium.ttf
  fonts:
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Medium.ttf
